### ISSUE TITLE
"y" property of text ignored

### ISSUE THREAD

**Issue by s0meRandomDev** [lmeysel/vue-svg-textwrap#1]
Hello ! The "y" property of the text seems to always be ignored. Example: 

```
<text  x="0"  y="0" dominant-baseline="hanging" v-wrapper="{ text: myTextValue, width: 200, align: 'none'}" />
```

Will give the same result as: 
```
<text  x="0"  y="50px" dominant-baseline="hanging" v-wrapper="{ text: myTextValue, width: 200, align: 'none'}" />
```

while the text should be 50px lower

**Comment by s0meRandomDev** [comment]
After further investigation, it appears to be because the `x` and `y` value of each of the generated `tspan` is set to `0`, while just not setting these value would have them inherit from the parent `text`

**Comment by lmeysel** [comment]
Good point, I am not sure why i set the y to 0, but your point is definitely correct. I fixed it.

**Comment by s0meRandomDev** [comment]
Awesome reactivity, thank you very much ! (works like a charm now)
